### ISSUE TITLE
Can't Determine HTTP Port when using homebridge-camera-ui

### ISSUE THREAD

**Issue by monza258** [Sunoo/homebridge-smtp-motion#111]
Hi, after update to 1.2.0 I can't use your Plugin. It missed the http _port option that I can set by my self. 
1.1.4 works fine.

**Comment by Sunoo** [comment]
It now reads the HTTP port from the homebridge-camera-ffmpeg plugin that is required to be set anyways.

**Comment by monza258** [comment]
I use your plugin in combination with the homebridge-camara-ui Plugin from Seydx. It need to set the http_port to get a Message.

**Comment by Sunoo** [comment]
Ah, I didn't consider that people used it with that. I will see about either reading their config or just allowing an override.

Will give it some thought today and determine the best way forward.

**Comment by Sunoo** [comment]
Added override_http in v1.2.1
