### ISSUE TITLE
MotionEyeOS camera not able to connect 

### ISSUE THREAD

**Issue by montanaishome** [Sunoo/homebridge-smtp-motion#115]
I have a camera on a pi running MotionEyeOS connected to my homebridge using the FFMPEG plugin.  Trying to expose the motion sensor.

Using this plugin, I get an error from MotionEye that “Notification Email Failed: Check SMTP port!”

See attached image.  I am using the IP address of my homebridge installation as the SMTP server.  Any idea what I am doing wrong?

Appreciate any assistance.  Thanks!

![C6570DEF-C3CF-45FB-8FAB-587B914F59CA](https://user- images.githubusercontent.com/41488348/112475175-2432ee00-8d36-11eb-9380-b7688c0280d1.png)

**Comment by montanaishome** [comment]
![386B2AB9-E42A-4315-8AB7-20B36942BF80](https://user-images.githubusercontent.com/41488348/112475678-b1764280-8d36-11eb-9f65-2b281aa42d40.png)

**Comment by Sunoo** [comment]
Anything in your Homebridge logs? You’ll likely  want to enable log emails for troubleshooting purposes too.

**Comment by Sunoo** [comment]
Also, I’ve never used MotionEye myself, but couldn’t you use their Webhook support to call homebridge-camera-ffmpeg’s HTTP endpoint directly? https://sunoo.github.io/homebridge-camera-ffmpeg/automation/http.html

**Comment by montanaishome** [comment]
Thanks.  I’ll give that a try.

Aaron Weissman
***@***.***
