### ISSUE TITLE
Motion sensor not turning on

### ISSUE THREAD

**Issue by jandreaucodes** [Sunoo/homebridge-smtp-motion#131]
I've got homebridge-smtp-motion and homebridge-camera-ffmpeg both running. Here is my config:

```
{
            "name": "Camera FFmpeg",
            "porthttp": 8080,
            "cameras": [
                {
                    "name": "DrivewayCam",
                    "manufacturer": "xxxx",
                    "model": "xxxx",
                    "motion": true,
                    "doorbell": true,
                    "switches": true,
                    "motionTimeout": 60,
                    "motionDoorbell": true,
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-i rtsp://XXX@192.168.4.86:88:554/videoMain",
                        "maxWidth": 0,
                        "maxHeight": 0,
                        "maxFPS": 0,
                        "vcodec": "copy"
                    }
                },
                {
                    "name": "Door Test",
                    "manufacturer": "xxxx",
                    "model": "xxxx",
                    "motion": true,
                    "doorbell": true,
                    "switches": true,
                    "motionDoorbell": true,
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-i rtsp://XXX@192.168.5.10:88:554/videoMain",
                        "maxWidth": 0,
                        "maxHeight": 0,
                        "maxFPS": 0,
                        "vcodec": "copy"
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        },
        {
            "name": "SMTP Motion",
            "log_emails": true,
            "platform": "smtpMotion"
        }
```

When the cameras detect motion, they send the email (homebridge shows the email received).

I set up the automation in Home to trigger motion (and also tried doorbell) if the motion sensor is toggled on. But the motion sensor never toggles on.

Am I missing a step somewhere?

**Comment by Sunoo** [comment]
What email address are you sending your alert messages to?

**Comment by jandreaucodes** [comment]
DrivewayCam@example.com. Just testing with that one before rolling out to the other camera (and then adding more cameras to the mix).

**Comment by Sunoo** [comment]
Hmm… that should be tripping it… What if you turn on logging for Camera FFmpeg? You should see messages about turning motion sensors on and off then…

Also, is this Homebridge or HOOBS?

**Comment by jandreaucodes** [comment]
I'm in Homebridge.

Happy to turn on logging - can you point me to where I do that in the plugin?

**Comment by jandreaucodes** [comment]
Debugging enabled. I get nothing after the email is received.

Logs just show 
`[12/2/2021, 11:54:32 AM] [SMTP Motion] [mike] Email received.
[12/2/2021, 11:54:44 AM] [SMTP Motion] [mike] Email received.`

Nothing else happens after that.

**Comment by jandreaucodes** [comment]
I'm in homebridge. Here's the debug from the camera after enabling logging.

`[12/2/2021, 11:57:49 AM] [SMTP Motion] [mike] Email received.`

Doesn't seem to actually log anything.

Here's an update config, to make sure I turned on debug correctly.

```
     {
            "name": "Camera FFmpeg",
            "porthttp": 8080,
            "cameras": [
                {
                    "name": "DrivewayCam",
                    "manufacturer": "xxxx",
                    "model": "xxxx",
                    "motion": true,
                    "doorbell": true,
                    "switches": true,
                    "motionTimeout": 60,
                    "motionDoorbell": true,
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-i rtsp://xx:xxx@192.168.4.86:88:554/videoMain",
                        "maxWidth": 0,
                        "maxHeight": 0,
                        "maxFPS": 0,
                        "vcodec": "copy",
                        "debug": true
                    }
                }
```

**Comment by Sunoo** [comment]
Okay, I’ll have to take a look into the code and see if I can spot the issue then. From what I can see, you should be working but the message is getting lost between the two plugins somehow.

**Comment by jandreaucodes** [comment]
Appreciate it, thanks.

Happy to try anything or give you access to poke around in my homebridge setup.
