### ISSUE TITLE
Idea : Trigger a dummy switch instead of sending http to homebridge-camera-ffmpeg?

### ISSUE THREAD

**Issue by kp9928** [Sunoo/homebridge-smtp-motion#133]
Hi there - this isn't really an issue but an idea/suggestion

I am trying to make a switch that will let me control my camera rich notification better. Right now, I am able to arm/disarm the rich notifications by means of using the homekit built in "when nobody/somebody is home" condition. However I want to take it one step further, such that when I am in a particular room (eg. my study room), I still want rich notification to come from certain cameras. The condition of "when nobody/somebody is home" is nice but too limiting. There are some cameras that I still want notification from even if I am home (though not all)

I was hoping to do something like this by means of having this smtp motion trigger a dummy switch instead of going directly to homebridge-camera-ffmpeg http port. I would therefore be able to make an automation that if that dummy switch is triggered, i can make an additional check (eg. via another stateful dummy switch say ...called "Enable Camera 1 Notification") - to see if i want to trigger the switch associated with the camera that sends the rich notification. Is something like this possible ?

Alternatively - is it possible for enable homebridge-camera-ffmpeg to create sourceless dummy switch? That way, I can make this plugin trigger those dummy switch instead to achieve the same effect.

**Comment by Sunoo** [comment]
You aren’t the first to ask for this, and historically I’ve kinda considered it outside the scope of this plugin. However, it’s starting to feel like enough people may want it to warrant adding the feature.

**Comment by kp9928** [comment]
Thanks for considering this!! I'd be more than happy to help test it out :)
