### ISSUE TITLE
Can't get to work with Hoobs

### ISSUE THREAD

**Issue by kkissane0328** [Sunoo/homebridge-smtp-motion#134]
I have Camera FFmpeg set up on Hoops working fine. 

I set this up on Hoobs but upon start up I receive the log error 

1/19/2022, 3:57:30 PMSmtp Motion BridgeSMTP MotionERRORThe homebridge-camera-ffmpeg plugin must be installed and configured.

Seems like setup may be different on Hoobs vs Homebridge. Any help is appreciated.

**Comment by Sunoo** [comment]
Can you share your config for both this and Camera FFmpeg?

**Comment by kkissane0328** [comment]
Camera FFmpeg Bridge:

{
    "platform": "Camera-ffmpeg",
    "name": "Camera FFmpeg",
    "cameras": [
        {
            "name": "frontyard",
            "manufacturer": "Amcrest",
            "model": "5MP UltraHD",
            "serialNumber": "AMC060D3099705C467",
            "unbridge": false,
            "videoConfig": {
                "source": "-i rtsp://user:pw@IP:554/cam/realmonitor?channel=1&subtype=0",
                "stillImageSource": "-i http://user:pw@IP/cgi-bin/snapshot.cgi?chan=1",
                "maxWidth": 0,
                "maxHeight": 0,
                "maxFPS": 0,
                "maxBitrate": 4096,
                "forceMax": true,
                "vcodec": "copy",
                "audio": true,
                "debug": true
            },
            "motion": true,
            "switches": false
        },
        {
            "name": "backyard",
            "manufacturer": "Amcrest",
            "model": "5MP UltraHD",
            "serialNumber": "AMC060333D89805428",
            "unbridge": false,
            "videoConfig": {
                "source": "-i rtsp://admin:Kk032890@192.168.0.133:554/cam/realmonitor?channel=1&subtype=0",
                "stillImageSource": "-i http://admin:Kk032890@192.168.0.133/cgi-bin/snapshot.cgi?chan=1",
                "maxWidth": 0,
                "maxHeight": 0,
                "maxFPS": 0,
                "maxBitrate": 4096,
                "forceMax": true,
                "vcodec": "copy",
                "audio": true,
                "debug": true
            },
            "motion": true
        }
    ],
    "porthttp": 8080
}

Smtp Motion Bridge
{
    "platform": "smtpMotion",
    "name": "SMTP Motion",
    "smtp_port": 2525,
    "log_emails": true
}

**Comment by kkissane0328** [comment]
![Camera FFmpeg](https://user-images.githubusercontent.com/44796933/150378693-62d6d165-81df-4722-afb7-4bf9504b2998.png)
![Smtp Motion](https://user-images.githubusercontent.com/44796933/150378700-6880e21b-a519-4fef-8bba-a60a00fce5fd.png)

**Comment by Sunoo** [comment]
Interesting, it does sound like there is some issue with this plugin and HOOBS then. In the meantime, you could try setting `override_http` to `8080` in the config for SMTP Motion and see if that gets you working.

**Comment by kkissane0328** [comment]
I actually tried that and I do get the confirmation email line but the motion on the camera doesn't actually trip 

1/20/2022, 1:05:07 PMSmtp Motion Bridge starting
1/20/2022, 1:05:12 PMSmtp Motion BridgeLoaded plugin 'homebridge-smtp-motion'
1/20/2022, 1:05:12 PMSmtp Motion BridgeLoading 1 platforms...
1/20/2022, 1:05:12 PMSmtp Motion BridgeBridge is running on port 51886.
1/20/2022, 1:07:53 PMSmtp Motion BridgeSMTP Motion[frontyard] Email received.

**Comment by Sunoo** [comment]
If you set debug to true on the camera, it should log when motion alerts are received. Can you try that and see if anything shows up in your logs? I can’t think of a reason that HOOBS should break that…

**Comment by kkissane0328** [comment]
Even with the logs enabled I don't see a motion event. Even tried triggering the motion event with the switches. I can see motion in HomeKit but no evidence in logs. Very strange

**Comment by Sunoo** [comment]
Interesting, let me see what I can find out. I haven’t tested this as thoroughly on HOOBS as I have on Homebridge, but it should work…

**Comment by kkissane0328** [comment]
Any help is appreciated! You rock!

**Comment by effpi** [comment]
@kkissane0328 : for what it is worth, here is how I solved the issue which I encountered as well. 
As my camera could also use FTP to send alert, I installed the ftp plug-in (https://github.com/Sunoo/homebridge-ftp-motion) and it is working flawlessly.

**Comment by kkissane0328** [comment]
Not sure what changed but motion sensor is working all of a sudden

**Comment by Sunoo** [comment]
Interesting, I guess we can close this out for now. If you ever figure out what happened, let me know and maybe I’ll add it to the documentation or something.
