### ISSUE TITLE
Feature request: define "space" character in config

### ISSUE THREAD

**Issue by lukebrannon1** [Sunoo/homebridge-smtp-motion#17]
Hello, I have a camera that does not allow the "+" character as a recipient email address. Could a configurable option in this plugin be added that allows me to define another character besides "+"?

For example, my camera does allow "\_" to be used in the recipient email address, so if this plugin could replace "\_" (or any other defined character) with " " that would be excellent!

**Comment by Sunoo** [comment]
Good idea, should be easy enough to implement. I chose + initially because it is a valid character according to the specs, but I’m not surprised that some devices don’t fully follow those.

Will probably take a look into that this weekend.

**Comment by Sunoo** [comment]
Implemented in 1.1.3
