### ISSUE TITLE
Question about camera image

### ISSUE THREAD

**Issue by erickribeiro** [Sunoo/homebridge-smtp-motion#26]
Hi,

First of all, thanks for creating this plugin, this is exactly what I'm looking for to convert Reolink motion notifications to Homekit motion events. Awesome!

I'm hoping you could clarify the following statement included in the Readme, though, which I found faily ambiguous:

_"... currently only triggers alerts **after uploading an image into the folder with the same name as your camera.** The image is not currently stored anywhere."_

Do I need to upload an image somewhere in order for the plugin to work or is this referring to how the image included in the e-mail content itself is handled by the plugin? What does it mean that the image is uploaded to a folder but is not stored anywhere?

I really appreciate if you can clarify the instructions in the Readme.
Thanks!

**Comment by Sunoo** [comment]
Looks like I made a copy/paste error when I based the readme for this plugin off another of my plugins. No image upload is needed, just send an email to the SMTP server exposed by this plugin using the proper email address.

I’ll fix that readme shortly. Sorry for the confusion.

**Comment by erickribeiro** [comment]
Perfect, that makes sense.

By the way, I was able to set up the plugin with my Reolink cameras today, and it works great. Notifications are seamless and instant. Really awesome stuff. Thank you again!

**Comment by Sunoo** [comment]
Fantastic, glad it’s working for you.
