### ISSUE TITLE
Possibility to expose smtp sensor as a dummy switch?

### ISSUE THREAD

**Issue by kp9928** [Sunoo/homebridge-smtp-motion#41]
First of all - this is an awesome plugin! I'm loving it! - Basically all my cameras with smtp-capabilities are motion sensors now!

I would like to ask if its possible to expose the smtp sensor as a dummy switch instead of automatically triggering the motion switch on the ffmpeg plugin. 

The reason for this is I'm looking for a way to include an OR condition for my notification (There may be a better way to do this - if so kindly advise?). I'm looking to trigger motion alerts rich notifications when, using homekit standard conditions..
1. No one's at home
2. Specific time after sunset (eg. midnight to sunrise)
I'm looking for an "OR" condition for both the above to trigger my rich notification. 

Currently with the SMTP motion plugin - it directly triggers the ffmpeg motion switches -  but based on only one of the conditions, not when either one of them is triggered. (My cameras are set to send emails on motion detect 24/7).

I was thinking if this was exposed as a dummy switch, I could use two automation that would check for either conditions, and manually triggering the ffmpeg motion switch(?) - does this make sense?

Thanks!

**Comment by Sunoo** [comment]
So this is something that could be done, however, I’d have to think about how best to handle it and if I even want to. The biggest issue is that this plugin does not have a list of cameras, so it wouldn’t know which switches to expose. It basically passes that information onto homebridge-camera-ffmpeg and let’s that plugin do the final processing.
