### ISSUE TITLE
How to read message content

### ISSUE THREAD

**Issue by taaa22** [Sunoo/homebridge-smtp-motion#71]
Thank you for providing this plugin.

I have 3 cameras connected to the NVR.
When the motion-triggered the NVR sends the message to all camera name.

What I want to do is reading the message content and extract the camera name from it then I can run the HTTP-based Automation.

Can you please help me with reading the message content.

**Comment by Sunoo** [comment]
Currently it is only set up to match based on the email address.

I’m not familiar with what device you’re using, can you let me know what messages look like from it?

**Comment by taaa22** [comment]
I'm using Hikvision NVR with Hikvision camera.

The message looks like
------------------------------------------------------
This is an automatically generated e-mail from your NVR.

EVENT TYPE:    Motion Detected
EVENT TIME:    2020-11-26,22:47:37
NVR NAME:      Network Video Recorder
NVR S/N:       0820181228CCRRC83441619WCVU
CAMERA NAME(NUM):   Camera 03(D3) 
------------------------------------------------------

I was able to read the message and read the camera name and based on it I run the HTTP-based automation.
