### ISSUE TITLE
camera having troubles with authentication

### ISSUE THREAD

**Issue by ndraper** [Sunoo/homebridge-smtp-motion#83]
I have everything setup and working through an email client however when I try to setup the details in the camera it returns a failed authentication request invalid username or password. Unfortunately my cameras will not allow for no user/password. Is there anything that can be done to return a valid auth request?

**Comment by Sunoo** [comment]
The plugin will accept any username and password.

**Comment by ndraper** [comment]
Yes I have tried using any username and password and my camera still returns invalid auth.

Regards,


Nathan Draper
