### ISSUE TITLE
Not an Issue - Just a massive THANK YOU 

### ISSUE THREAD

**Issue by steverae68** [Sunoo/homebridge-smtp-motion#88]
I have set up this system with my HikVision camera's in association with Camera-ffmpeg and I've managed to get it to work flawlessly for all three of my camera's so I can use my Philips motion sensor somewhere else.

Thank you so much for this

**Comment by Sunoo** [comment]
Awesome, I’m glad that it’s working well for you!

**Comment by Murdrock** [comment]
Thank you for the insight! Never thought of that workaround!Whenever you are able to post it. I ll wait!

Cheers!
